# To copy the multiple files in a loop

---

- name: To copy a file to a remote host
  hosts: "*"
  tasks:
    - name: Copy files to remote host
      copy: 
        src: "file/{{ item }}"
        dest: "$HOME/{{ item }}"
      loop:
        - test-1.txt
        - test-2.txt
        - test-3.txt