---
- name: To install phpmyadmin
  hosts: 192.168.1.29
  tasks:
    - name: Install php
      apt: name=php state=present
      # with_items:
      #   - php
      #   - php-fpm
      #   - php-mysql
      #   - php-curl

    - name: restart php
      service: name=php state=restarted