---

# to print a html webpage

- name: webserver playbook
  hosts: all
  become: true
  tasks:

    # - name: install nginx
    #   apt: name=nginx

    - name: enable and start nginx
      service: name=nginx state=started

    # - name: creating the index.html
    #   copy: 
    #     content: "Welcome to nginx"
    #     dest: /var/www/html/index.html
    #     mode: 0444