---

# ansible script to create multiple directories

- name: run tasks on all hosts
  hosts: "*"
  tasks:
    - name: to remove directory
      file:
        path: $HOME/ansible-project
        state: directory
      loop:
        - ansi_dir1
        - ansi_dir2
        - ansi_dir3

