---
- hosts: localhost
  tasks:
    - name: ensure vim is at the latest version
      become: yes
      apt: name=vim state=latest
      #become_pass: H1@2R3$4H5
    - name: start vim
      service:
          name: vi
          state: started
      #become: yes